pipeline {
    agent any

    stages {
        stage('Fetch Docker Image') {
            steps {
                sh 'docker login ghcr.io -u wasabi805 -p ${GITHUB_TOKEN}'
                sh 'docker pull ghcr.io/wasabi805/my_test_of_build_image:latest'
            }
        }
        stage('Build Docker Image') {
            steps {
                sh 'docker build -t my_test_of_build_image .'
            }
        }
        stage('Push Docker Image') {
            steps {
                sh 'docker tag my_test_of_build_image:latest ghcr.io/wasabi805/my_test_of_build_image:latest'
                sh 'docker push ghcr.io/wasabi805/my_test_of_build_image:latest'
            }
        }
    }
}